# Generated by Django 6.0.2 on 2026-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_series_video_genre_video_is_movie_video_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.TextField(blank=True, help_text='Comma-separated list of cast members', null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 2h 30m', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='subtitles',
            field=models.CharField(blank=True, help_text='Comma-separated subtitle languages', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='cast',
            field=models.TextField(blank=True, help_text='Comma-separated list of cast members', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 2h 30m', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles',
            field=models.CharField(blank=True, help_text='Comma-separated subtitle languages', max_length=255, null=True),
        ),
    ]
